# Generated by Django 4.0.3 on 2022-09-06 09:44

from django.db import migrations, models
import django.db.models.deletion
import todo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auteur',
            name='num_phone',
            field=models.CharField(default=25772037069, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=todo_app.models.apres_une_semaine)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.auteur', to_field='user')),
            ],
        ),
    ]
